version: '3.8'

services:
  database:
    image: postgres:${POSTGRES_VERSION:-12}-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-strana}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-strongPAS}
      POSTGRES_USER: ${POSTGRES_USER:-webmaster}
    ports:
      - ${POSTGRES_PORT:-5432}:5432
  redis:
    image: redis:alpine
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - ${REDIS_PORT:-6379}:6379

volumes:
  pg_data: ~
