kind: ConfigMap
apiVersion: v1
metadata:
  name: backend-host-config
  namespace: strana-sup
  labels:
    app: sup
    tier: backend
data:
  default.conf: |
    server {
      listen       80 default_server;
      server_name sup.strana.t.crtweb.ru;
      root /app;
      
      location /static/ {
        try_files $uri =404;
      }
      location /media/ {
        try_files $uri =404;
      }
      location / {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header  X-Forwarded-Proto https;
        proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header  X-Forwarded-Referrer $http_referer;
        proxy_set_header  Referer $http_referer;
        proxy_redirect off;
        proxy_pass http://localhost:8000;
      } 
    }
